# Feature scaling with sklearn - Exercise

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. This exercise is very similar to a previous one. This time, however, **please standardize the data**.

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
sns.set()
from sklearn.preprocessing import StandardScaler

## Load the data

In [3]:
data = pd.read_csv("real_estate_price_size_year.csv")

In [4]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Create the regression

### Declare the dependent and the independent variables

In [5]:
y = data['price']
x = data[['size','year']]

### Scale the inputs

In [7]:
scalar = StandardScaler()
scalar.fit(x)
x_scaled = scalar.transform(x)
x_scaled


C:\Users\Prachi\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Prachi\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

### Regression

In [8]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

### Find the intercept

In [9]:
reg.intercept_

292289.4701599997

### Find the coefficients

In [10]:
reg.coef_

array([67501.57614152, 13724.39708231])

### Calculate the R-squared

In [11]:
reg.score(x_scaled,y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [13]:
x.shape

(100, 2)

In [14]:
n = x.shape[0]
p = x.shape[1]
r2 = reg.score(x_scaled,y)

In [15]:
adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [16]:
adj_r2

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

Answer... since the values are close that means adding new variable doesnt bring any significant change 

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Answer... year is not putting any significant effect so we can remove it 

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [22]:
new_data = pd.DataFrame(data = [[750,2009]], columns = ['size','year'])
new_data

size  year
0   750  2009

In [23]:
reg.predict(new_data)

array([78490785.31465863])

In [24]:
new_data_scaled = scalar.transform(new_data)

C:\Users\Prachi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [25]:
new_data_scaled

array([[-0.34752816, -0.76509206]])

In [26]:
reg.predict(new_data_scaled)

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [27]:
f_regression(x_scaled,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [31]:
p_values = f_regression(x_scaled,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [32]:
p_values.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [33]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
reg_summary['Coefficient'] = reg.coef_
reg_summary['P Values'] = p_values.round(3)
reg_summary

Features   Coefficient  P Values
0     size  67501.576142     0.000
1     year  13724.397082     0.357

Answer...